# Generated by Django 2.2 on 2019-04-09 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('subcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('code', models.CharField(max_length=7)),
                ('vendor', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category')),
            ],
            options={
                'verbose_name_plural': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='PlantSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_string', models.CharField(max_length=50)),
                ('code_string', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpecifiedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40)),
                ('subcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Equipment')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Size')),
            ],
            options={
                'verbose_name_plural': 'specified equipment',
            },
        ),
        migrations.CreateModel(
            name='TaggedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('subcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('code', models.CharField(max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('specified_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.SpecifiedEquipment')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.PlantSystem')),
            ],
            options={
                'verbose_name_plural': 'tagged equipment',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category')),
            ],
            options={
                'verbose_name_plural': 'sub categories',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.SubCategory'),
        ),
    ]
