# Generated by Django 2.2 on 2019-04-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='TaggedEquipment',
        ),
        migrations.AlterModelOptions(
            name='taggedequipment',
            options={'verbose_name_plural': 'tagged equipment'},
        ),
    ]
