# Generated by Django 2.2 on 2019-04-01 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190401_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
