# Generated by Django 2.2 on 2019-04-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190401_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
