# Generated by Django 2.2 on 2019-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190401_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='subcode',
            field=models.CharField(default='1001', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
