# Generated by Django 2.2 on 2019-04-02 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190402_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='subcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
