# Generated by Django 2.2 on 2019-04-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190402_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_string', models.CharField(max_length=50)),
                ('code_string', models.CharField(max_length=10)),
            ],
        ),
    ]
