# Generated by Django 2.2 on 2019-04-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedequipment',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Size'),
        ),
    ]
