# Generated by Django 2.2 on 2019-04-02 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190402_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedequipment',
            name='subcode',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
            preserve_default=False,
        ),
    ]
