# Generated by Django 2.2 on 2019-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_taggedequipment_subcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
