# Generated by Django 2.2 on 2019-04-02 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190402_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='taggedequipment',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
